export const glossaryTerms = [
  ["Amortizing", "A loan paid down over time through scheduled monthly payments."],
  ["Appraisal", "A professional estimate of a home's market value for the lender."],
  ["Closing Disclosure", "A final document showing loan terms, payment, fees, and cash to close."],
  ["Contingency", "A contract condition that must be met for the sale to move forward."],
  ["Debt-to-Income Ratio", "The share of your monthly income used for debt payments."],
  ["Deferred Loan", "A loan with no monthly payments until a future event, such as sale or refinance."],
  ["Down Payment", "Money paid upfront toward the home purchase price."],
  ["Earnest Money", "A deposit showing the seller your offer is serious."],
  ["Escrow", "A holding account for taxes, insurance, or transaction funds."],
  ["Fixed Rate", "An interest rate that stays the same for the life of the loan."],
  ["Great Choice", "THDA's 30-year fixed rate mortgage program for eligible Tennessee buyers."],
  ["Great Choice Plus", "Optional down payment assistance paired with a Great Choice mortgage."],
  ["Home Inspection", "A buyer-paid review of the home's condition before closing."],
  ["Income Limits", "Maximum household income rules for program eligibility."],
  ["Loan Estimate", "An early lender form showing estimated costs and loan terms."],
  ["Pre-Approval", "A lender's conditional statement that you may qualify for a loan amount."],
  ["Principal", "The amount borrowed before interest."],
  ["Rate Lock", "A lender commitment to hold an interest rate for a set period."],
  ["Refinance", "Replacing your current mortgage with a new one."],
  ["THDA", "Tennessee Housing Development Agency, which offers Great Choice programs."],
  ["Title Search", "A review confirming legal ownership and claims on the property."],
  ["Underwriting", "The lender's review of your credit, income, assets, and property."]
] as const;
